name: 'Secret Injector'
description: 'GitHub Action to inject Secrets & env values referenced in all project files'
inputs:
  secrets:
    description: 'Workflow secrets'
    required: false
    default: "undefined"
  env:
    description: 'Workflow env'
    required: false
    default: "undefined"
runs:
  using: 'node12'
  main: 'index.js'