---
name: "Tests"

on: [push]
env:
  cake: ${{ secrets.enviroment_cake }}
  cube: sentient

jobs:
  TestAction:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Injector Action
        uses: ./
        with:
          secrets: ${{ toJson(secrets) }}
          env: ${{ toJson(env) }}

      - name: Validate testFile.json has correct content
        with:
          secrets: ${{ toJson(secrets) }}
          env: ${{ toJson(env) }}
        run: |
          npm test