on: [push]
env:
  cake: ${{ secrets.enviroment_cake }}
  cube: sentient

jobs:
  TestAction:
    runs-on: ubuntu-latest
    name: Test action is working
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Injector Action
        uses: ./
        with:
          secrets: ${{ toJson(secrets) }}
          env: ${{ toJson(env) }}

      - name: Echo testFile.json contents
        run: echo cat testFile.json

      - name: Validate testFile.json has correct content
        run: |
          echo ${{ toJson(secrets) }} >> .secrets.json
          echo ${{ toJson(env) }} >> .env.json
          npm test