---
name: "Tests"

on: [push]
env:
  cake: ${{ secrets.enviroment_cake }}
  cube: sentient

jobs:
  TestAction:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Injector Action
        uses: ./
        with:
          secrets: ${{ toJson(secrets) }}
          env: ${{ toJson(env) }}

      - name: Write out env and secrets to .secrets & .env to validate.
        run: |
          printf "${{ toJson(toJson(secrets)) }}" >> .secrets.json
          printf "${{ toJson(toJson(env)) }}" >> .env.json

      - name: Validate testFile.json has correct content
        run: |
          npm test